### ISSUE TITLE
Complete serializations table

### ISSUE THREAD

**Issue by dorianvp** [dorianvp/zcash-wallet-formats#8]
- [x] CAccount
- [x] CPubKey
- [x] CPrivKey
- [x] CKeyMetadata
- [x] CMasterKey
- [x] CAccountingEntry
- [x] CBlockLocator
- [x] CKeyPool
- [x] CHDChainV3
- [x] CHDChainV5
- [x] RawHDSeed
- [x] COutPoint
- [x] SaplingOutPoint
- [x] CTxIn
- [x] CTxOut
- [x] JSOutPoint
- [x] SproutNoteData
- [x] IncrementalMerkleTree<Depth, Hash>
- [x] IncrementalWitness<Depth, Hash>
- [x] libzcash::PedersenHash
- [x] SaplingWitness
- [x] SaplingNoteData
- [x] CompressedG1
- [x] CompressedG2
- [x] libzcash::GrothProof
- [x] libzcash::PHGRProof
- [x] SpendDescription
- [x] libzcash::SaplingEncCiphertext
- [x] libzcash::SaplingOutCiphertext
- [x] OutputDescription
- [x] JSDescription
- [x] libzcash::OrchardIncomingViewingKey
- [x] OrchardWalletTxMeta
- [x] [CTransaction](https://github.com/dorianvp/zcash-wallet-formats/issues/9) (depends on SaplingV4Writer)
- [x] CMerkleTx (depends on #9)
- [x] [CWalletTx](https://github.com/dorianvp/zcash-wallet-formats/issues/10)
- [x] SaplingBundle
- [x] OrchardBundle
- [x] SaplingV4Writer
- [x] ed25519::VerificationKey
- [x] ed25519::Signature
- [x] libzcash::SaplingFullViewingKey
- [x] libzcash::SaplingExpandedSpendingKey
- [x] libzcash::SaplingIncomingViewingKey
- [x] libzcash::SaplingExtendedFullViewingKey
- [x] libzcash::SaplingExtendedSpendingKey
- [x] libzcash::SaplingPaymentAddress
- [x] libzcash::OrchardRawAddress
- [x] libzcash::SproutPaymentAddress
- [x] libzcash::SproutViewingKey
- [x] libzcash::SproutSpendingKey
- [x] CScriptBase
- [x] libzcash::SeedFingerprint
- [x] libzcash::AccountId
- [x] libzcash::UFVKId
- [x] libzcash::ReceiverType
- [x] ZcashdUnifiedAccountMetadata
- [x] ZcashdUnifiedAddressMetadata
- [x] Address
- [x] MerkleBridge
- [x] BridgeTree
- [x] [OrchardWalletNoteCommitmentTreeWriter](https://github.com/dorianvp/zcash-wallet-formats/issues/11)
- [x] [libzcash::UnifiedFullViewingKey::Encode(string, UnifiedFullViewingKeyPtr)](https://github.com/dorianvp/zcash-wallet-formats/issues/12)
- [x] MnemonicSeed
- [x] ReceiverTypeSer
- [x] CSerializeRecipientAddress

**Comment by dorianvp** [comment]
I'm marking this as completed. However, `libzcash::UnifiedFullViewingKey::Encode` and other types might still require further clarification or a more detailed explanation. If needed, this issue will be reopened.
